<?php
/**
* English file for plugin djg_cf
*
* @package wolf
* @subpackage djg_cf
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgCfController.php */ 
'The settings have been updated.' => 'The settings have been updated.', 
'Massage from:' => 'Massage from:', 
'The Subject:' => 'The Subject:', 
'The Message:' => 'The Message:', 
/** enable.php */ 
'djg_cf - plugin settings initialized.' => 'djg_cf - plugin settings initialized.', 
'djg_cf - unable to store plugin settings!' => 'djg_cf - unable to store plugin settings!', 
/** index.php */ 
'[djg] Contact form' => '[djg] Contact form', 
'Ajax contact form' => 'Ajax contact form', 
'I don\'t talk to strangers.' => 'I don\'t talk to strangers.', 
'You don\'t want me to answer?' => 'You don\'t want me to answer?', 
'What is the purpose of the contact?' => 'What is the purpose of the contact?', 
'Forgot why you came here?' => 'Forgot why you came here?', 
'Issue required.' => 'Issue required.', 
'Your Name:' => 'Your Name:', 
'Your Email:' => 'Your Email:', 
'Select a subject' => 'Select a subject', 
'The Captcha:' => 'The Captcha:', 
'captcha image' => 'captcha image', 
'Send The Message' => 'Send The Message', 
'Thank you. The mailman is on his way.' => 'Thank you. The mailman is on his way.', 
'Sorry, don\'t know what happened. Try later.' => 'Sorry, don\'t know what happened. Try later.', 
'Probability JavaScript is disabled or You have not jQuery library.' => 'Probability JavaScript is disabled or You have not jQuery library.', 
/** views\documentation.php */ 
'Djg Contact Form Documentation' => 'Djg Contact Form Documentation', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'E-mail adress' => 'E-mail adress', 
'Your e-mail adress' => 'Your e-mail adress', 
'Subject prefix' => 'Subject prefix', 
'Subject prefix <br />for example: <strong>"Message frow www, topic: "</strong>' => 'Subject prefix <br />for example: <strong>"Message frow www, topic: "</strong>', 
'Auto append css' => 'Auto append css', 
'Yes' => 'Yes', 
'No' => 'No', 
'Choose yes if you want to automatically append <br />example css file to <strong>HEAD</strong> after init.<br /><code>:fl</code>' => 'Choose yes if you want to automatically append <br />example css file to <strong>HEAD</strong> after init.<br /><code>:fl</code>', 
'Use captcha' => 'Use captcha', 
'Choose yes if you want to use a captcha to protect yourself against spammers.' => 'Choose yes if you want to use a captcha to protect yourself against spammers.', 
'Use subject' => 'Use subject', 
'Choose yes if you want to use a subjects in your form.' => 'Choose yes if you want to use a subjects in your form.', 
'Subjects:' => 'Subjects:', 
'add subject' => 'add subject', 
'remove subject' => 'remove subject', 
'List of all avalible subjects of message. <br />Blanks inputs will be skipped.' => 'List of all avalible subjects of message. <br />Blanks inputs will be skipped.', 
'Save' => 'Save', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views\sidebar.php */ 
'Documentation' => 'Documentation', 
);